id: P008000
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:54:17.937456
source_metadata:
  id: bdr:W2CZ8010
  title: སེར་སྨད་ཟུར་བཀོལ་སྤྱི་མཐའ།
  author: ''
  volumes:
    36204a0462a94a36a776c1af70bdaadc:
      image_group_id: I1PD96582
      title: Volume 1 of ser smad zur bkol spyi mtha'
      volume_number: 1
      total_pages: 636
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
