id: P008000
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8010
  title: སེར་སྨད་ཟུར་བཀོལ་སྤྱི་མཐའ།
  author: ''
  volumes:
    8b1d3085c5c548c89e780223a0fd7e27:
      image_group_id: I1PD96582
      title: ''
      volume_number: 1
      total_pages: 636
ebook_metadata:
  title: སེར་སྨད་ཟུར་བཀོལ་སྤྱི་མཐའ།
  author: ''
  sku: P008000
  cover: cover.jpg
  layers:
  - pagination
